# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            anno6882
tagline:          yet another tech blog
url:              http://http://anno6882.github.io/
paginate:         3
baseurl:          /
author:
  name:           anno6882
  url:            http://http://anno6882.github.io/
  email:          h5zbt@notsharingmy.info

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/anno6882/anno6882.github.io
  
# This is the list of pages to include in the header of the website.
pages_list:       {'Archive':'/archive'}
